title: Saagar Jha
email: saagar@saagarjha.com
description: "Saagar Jha's website."
url: "https://saagarjha.com"
enforce_ssl: saagarjha.com
github_username: saagarjha
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: true
permalink: /blog/:year/:month/:day/:title/
collections:
  showcase:
  projects:
    permalink: /projects/:title/
  toys:
    permalink: /toys/:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
whitelist:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
