title: Saagar Jha
email: saagar@saagarjha.com
description: >
  Saagar Jha's website, projects he's worked on, blog, and cool facts about him.
url: "http://saagarjha.com"
github_username:  saagarjha
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
permalink: /blog/:year/:month/:day/:title/
collections:
  showcase:
  projects:
    output: true
    permalink: /projects/:path/
  toys:
    output: true
    permalink: /toys/:path/
gems:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
exclude:
  - Gemfile
  - Gemfile.lock